"""build_initial_index.py — generate knowledge/index.md from existing articles.

compile.py builds the index incrementally as daily logs are processed. After
the one-time `migrate.py` import, there are concepts but no daily log to
trigger compilation, so the index stays empty.

This script scans knowledge/concepts/, knowledge/connections/, knowledge/qa/,
knowledge/compounds/, and knowledge/debugging/ to produce an initial index
table. Idempotent — overwrites index.md each run.

Usage:
    uv run python scripts/build_initial_index.py
"""

from __future__ import annotations

import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
KNOWLEDGE = ROOT / "knowledge"


def parse_frontmatter(text: str) -> dict:
    """Naïve YAML frontmatter parser: flat key:value pairs only."""
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---\n", 4)
    if end == -1:
        return {}
    fm: dict[str, str] = {}
    for line in text[4:end].splitlines():
        if not line.strip() or line.startswith("#") or ":" not in line:
            continue
        key, _, value = line.partition(":")
        fm[key.strip()] = value.strip().strip('"').strip("'")
    return fm


def first_paragraph(text: str) -> str:
    """First non-frontmatter paragraph, used as a description fallback."""
    body = text
    if text.startswith("---\n"):
        end = text.find("\n---\n", 4)
        if end != -1:
            body = text[end + 5 :]
    body = body.lstrip("\n")
    # Skip the H1 line if present
    if body.startswith("#"):
        nl = body.find("\n")
        if nl != -1:
            body = body[nl + 1 :].lstrip("\n")
    # Take everything up to the next blank line
    para = re.split(r"\n\s*\n", body, maxsplit=1)[0].strip()
    # Collapse internal whitespace
    para = re.sub(r"\s+", " ", para)
    return para[:200]


def main() -> int:
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

    if not KNOWLEDGE.is_dir():
        sys.stderr.write(f"[index] knowledge/ not found at {KNOWLEDGE}\n")
        return 2

    rows: list[tuple[str, str, str, str]] = (
        []
    )  # (article_path, summary, sources, updated)
    for subdir_name in ("concepts", "connections", "qa", "compounds", "debugging"):
        subdir = KNOWLEDGE / subdir_name
        if not subdir.is_dir():
            continue
        for md in sorted(subdir.rglob("*.md")):
            try:
                text = md.read_text(encoding="utf-8")
            except Exception:
                continue
            fm = parse_frontmatter(text)
            # Build the wikilink path relative to knowledge/
            rel = md.relative_to(KNOWLEDGE).with_suffix("")
            # Normalize Windows separators
            wikilink = "[[" + str(rel).replace("\\", "/") + "]]"
            description = fm.get("description") or first_paragraph(text)
            sources = fm.get(
                "sources", ""
            )  # multi-line YAML lists won't parse; fallback ""
            if not sources:
                # Fallback: list any "legacy:..." pointer found
                sources_match = re.search(r"legacy:[\w_.-]+\.md", text)
                sources = sources_match.group(0) if sources_match else "—"
            updated = fm.get("updated") or fm.get("created") or date.today().isoformat()
            rows.append((wikilink, description, sources, updated))

    if not rows:
        sys.stderr.write("[index] no articles found in knowledge/, nothing to write\n")
        return 1

    today = date.today().isoformat()
    lines = [
        "# Knowledge Base Index",
        "",
        f"_Auto-generated by build_initial_index.py on {today}. compile.py will incrementally update this on each daily-log compile._",
        "",
        f"**{len(rows)} articles** across concepts, connections, qa, compounds, debugging.",
        "",
        "| Article | Summary | Source | Updated |",
        "|---------|---------|--------|---------|",
    ]
    for wikilink, summary, source, updated in rows:
        # Pipe characters in the summary would break the markdown table
        safe_summary = summary.replace("|", "\\|")
        safe_source = source.replace("|", "\\|")
        lines.append(f"| {wikilink} | {safe_summary} | {safe_source} | {updated} |")

    index_path = KNOWLEDGE / "index.md"
    index_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    sys.stdout.write(f"[index] wrote {index_path} with {len(rows)} entries\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
